
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: manage_product_development

test:
  <<: *default
  database: manage_product_test

production:
  <<: *default
  password: manage_product_production
